name: Deploy to Shared Hosting
on:
  push:
    branches:
      - main # Change this to your main branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Use the version of Node.js your project requires
      - name: Install project dependencies
        run: npm install
        working-directory: ./
      - name: Build React project
        run: npm run build
        working-directory: ./
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install lftp
      - name: Deploy to Shared Hosting using FTP
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
        run: |
          cd build
          lftp -c "set ssl:verify-certificate no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -R -e -x .git/ ./"
      - name: Clean up
        run: |
          # Clean up any temporary files or do post-deployment cleanup
